language: cpp

matrix:
  include:

    - os: linux
      compiler: gcc
      name: ubuntu 14.04 - gcc@7.0
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      compiler: gcc
      name: ubuntu - gcc
      addons:
        apt:
          sources:
            ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      compiler: clang
      name: ubuntu 14.04 - clang@6.0
      dist: trusty
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-6.0
            - libstdc++-7-dev
            - libclang-6.0-dev
            - libopencv-dev

      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"

before_install:
  - travis_retry eval "${MATRIX_EVAL}"

install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo softwareupdate -l                                                                              ;fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1"             ;fi
  # CMake upgrade

  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.1-Darwin-x86_64.tar.gz        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then tar -xzf cmake-3.13.1-Darwin-x86_64.tar.gz                                                         ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then export PATH=$PWD/cmake-3.13.1-Darwin-x86_64/CMake.app/Contents/bin:$PATH                           ;fi
  ###############################################################################################################################################
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz         ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.13.1-Linux-x86_64.tar.gz                                                          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.13.1-Linux-x86_64/bin:$PATH                                               ;fi

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake "-DCMAKE_BUILD_TYPE=Release" "-DVIEWER=ON" ..

script:
  - cmake --build . --target install

after_success:
  - codecov --file coverage/lcov.info --disable search
